[package]
name = "spall_ecology"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
blake3.workspace = true
spall_core.workspace = true
spall_voxel.workspace = true
spall_worldgen.workspace = true
thiserror.workspace = true

serde.workspace = true
postcard.workspace = true
