//! @generated by `cargo run -p spall_editor --example appearance_palette`.
//! Append-only: the generator keeps every row and adds new ones; never renumber
//! or recolour a row (that needs a versioned manifest migration).

/// `(id, portable material key, name, authored sRGB tint)`; ids start at
/// `appearance::EXTENSION_ID_BASE` and only grow.
pub const EXTENSIONS: &[(u16, &str, &str, [u8; 3])] = &[];
