[package]
name = "spall_fluid"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
salva3d = { path = "../../vendor/salva3d", version = "=0.10.0" }
rayon = { path = "../../vendor/parallel/rayon-1.12.0", version = "=1.12.0" }
spall_core.workspace = true
spall_voxel.workspace = true
thiserror.workspace = true

[features]
salva-parallel = ["salva3d/parallel"]
allocation-diagnostics = []

[[bin]]
name = "fluid-scenario"
path = "src/bin/fluid_scenario.rs"

[[bin]]
name = "grid-fluid-scenario"
path = "src/bin/grid_fluid_scenario.rs"
